---
- hosts: webserver
  become: true
  tasks:
    - name: Install Apache
      apt:
        name: apache2  # Change the package name to 'apache2'
        state: present
    - name: Start Apache server
      service:
        name: apache2  # Change the service name to 'apache2'
        state: started
        enabled: true  # Change 'enable' to 'enabled'
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html
