---
- hosts: webserver
  become: true
  tasks:
    - name: Install Apache
      apt:
        name: httpd
        state: present
    - name: Start Apache server
      service: 
        name: httpd
        state: started
        enable: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html
